export interface Player {
  id: number
  name: string
  position: string
  gradYear: number
  division: string
  location: string
  tags: string[]
  image: string
  bio: string
  height: string
  weight: string
  gpa: string
  stats: { label: string; value: string }[]
}

export const players: Player[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    position: 'Point Guard',
    gradYear: 2025,
    division: 'D1',
    location: 'Tennessee',
    tags: ['All-State', 'Team Captain', 'Academic Excellence'],
    image: '/images/placeholder-player.svg',
    bio: 'Four-year varsity starter with exceptional court vision and leadership. Led team to state championships in 2024. Known for high basketball IQ and ability to control the tempo of the game.',
    height: "5'8\"",
    weight: '145 lbs',
    gpa: '3.9',
    stats: [
      { label: 'PPG', value: '18.5' },
      { label: 'APG', value: '7.2' },
      { label: 'SPG', value: '2.8' },
      { label: 'FG%', value: '47' },
    ],
  },
  {
    id: 2,
    name: 'Maria Rodriguez',
    position: 'Shooting Guard',
    gradYear: 2026,
    division: 'D2',
    location: 'California',
    tags: ['3-Point Specialist', 'Leadership', 'NIL Ready'],
    image: '/images/placeholder-player.svg',
    bio: 'Elite shooter with deep range and quick release. Three-point contest champion at 2025 Elite GBB showcase. Active in community outreach and brand building.',
    height: "5'10\"",
    weight: '150 lbs',
    gpa: '3.7',
    stats: [
      { label: 'PPG', value: '22.1' },
      { label: '3P%', value: '42' },
      { label: 'RPG', value: '5.3' },
      { label: 'FT%', value: '89' },
    ],
  },
  {
    id: 3,
    name: 'Emma Davis',
    position: 'Center',
    gradYear: 2024,
    division: 'D1',
    location: 'Texas',
    tags: ['Dominant Rebounder', 'Block Specialist', 'Scholar Athlete'],
    image: '/images/placeholder-player.svg',
    bio: 'Dominant post presence with soft touch around the rim. Two-time Defensive Player of the Year. National Honor Society member with aspirations in sports medicine.',
    height: "6'2\"",
    weight: '175 lbs',
    gpa: '4.0',
    stats: [
      { label: 'PPG', value: '16.8' },
      { label: 'RPG', value: '12.4' },
      { label: 'BPG', value: '3.1' },
      { label: 'FG%', value: '55' },
    ],
  },
  {
    id: 4,
    name: 'Aaliyah Williams',
    position: 'Small Forward',
    gradYear: 2025,
    division: 'D1',
    location: 'Georgia',
    tags: ['Versatile Defender', 'High Motor', 'Clutch Performer'],
    image: '/images/placeholder-player.svg',
    bio: 'Versatile wing who can guard all five positions. Averaged a double-double in her junior season. Known for taking over games in the fourth quarter.',
    height: "5'11\"",
    weight: '155 lbs',
    gpa: '3.5',
    stats: [
      { label: 'PPG', value: '15.2' },
      { label: 'RPG', value: '8.1' },
      { label: 'APG', value: '3.5' },
      { label: 'STL%', value: '3.2' },
    ],
  },
  {
    id: 5,
    name: 'Olivia Chen',
    position: 'Point Guard',
    gradYear: 2027,
    division: 'D3',
    location: 'Oregon',
    tags: ['Rising Star', 'Playmaker', 'High IQ'],
    image: '/images/placeholder-player.svg',
    bio: 'Young floor general with elite passing ability and basketball IQ beyond her years. Started varsity as a freshman and immediately made an impact.',
    height: "5'6\"",
    weight: '135 lbs',
    gpa: '4.0',
    stats: [
      { label: 'PPG', value: '12.8' },
      { label: 'APG', value: '8.9' },
      { label: 'TO', value: '1.8' },
      { label: 'AST/TO', value: '4.9' },
    ],
  },
  {
    id: 6,
    name: 'Jordan Taylor',
    position: 'Power Forward',
    gradYear: 2025,
    division: 'D1',
    location: 'New York',
    tags: ['Stretch Forward', 'Rebounder', 'Team Player'],
    image: '/images/placeholder-player.svg',
    bio: 'Modern stretch forward with the ability to score inside and out. Excellent rebounder who runs the floor well. Team captain with natural leadership qualities.',
    height: "6'0\"",
    weight: '165 lbs',
    gpa: '3.6',
    stats: [
      { label: 'PPG', value: '14.5' },
      { label: 'RPG', value: '9.2' },
      { label: '3P%', value: '38' },
      { label: 'BLK', value: '1.5' },
    ],
  },
  {
    id: 7,
    name: 'Maya Thompson',
    position: 'Shooting Guard',
    gradYear: 2026,
    division: 'D2',
    location: 'Florida',
    tags: ['Athletic Finisher', 'Lockdown Defender', 'NIL Ready'],
    image: '/images/placeholder-player.svg',
    bio: 'Explosive guard who can finish above the rim and defend at a high level. Built a strong personal brand through social media and community involvement.',
    height: "5'9\"",
    weight: '148 lbs',
    gpa: '3.3',
    stats: [
      { label: 'PPG', value: '19.4' },
      { label: 'RPG', value: '4.8' },
      { label: 'SPG', value: '3.0' },
      { label: 'FG%', value: '49' },
    ],
  },
  {
    id: 8,
    name: 'Brooke Anderson',
    position: 'Center',
    gradYear: 2025,
    division: 'D1',
    location: 'Illinois',
    tags: ['Shot Blocker', 'Low Post Scorer', 'Honor Roll'],
    image: '/images/placeholder-player.svg',
    bio: 'True back-to-the-basket center with polished post moves. Led the state in blocked shots for two consecutive seasons. Honor roll student committed to academic excellence.',
    height: "6'3\"",
    weight: '180 lbs',
    gpa: '3.8',
    stats: [
      { label: 'PPG', value: '13.6' },
      { label: 'RPG', value: '11.8' },
      { label: 'BPG', value: '4.2' },
      { label: 'FG%', value: '58' },
    ],
  },
  {
    id: 9,
    name: 'Kylie Martinez',
    position: 'Small Forward',
    gradYear: 2027,
    division: 'D2',
    location: 'Arizona',
    tags: ['Versatile Scorer', 'High Energy', 'Gym Rat'],
    image: '/images/placeholder-player.svg',
    bio: 'High-energy forward who scores at all three levels. Outworks everyone in practice and study. Raw talent with tremendous upside and work ethic.',
    height: "5'10\"",
    weight: '152 lbs',
    gpa: '3.4',
    stats: [
      { label: 'PPG', value: '17.3' },
      { label: 'RPG', value: '7.5' },
      { label: 'APG', value: '2.9' },
      { label: 'FG%', value: '51' },
    ],
  },
]
