-- Tournaments, Events, Programs tables
CREATE TABLE IF NOT EXISTS tournaments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', address text NOT NULL DEFAULT '', start_date timestamptz, end_date timestamptz, registration_deadline timestamptz, entry_fee numeric(10,2) NOT NULL DEFAULT 0, max_teams integer NOT NULL DEFAULT 0, current_teams integer NOT NULL DEFAULT 0, age_groups text[] NOT NULL DEFAULT '{}', divisions text[] NOT NULL DEFAULT '{}', format text NOT NULL DEFAULT '', prize_description text NOT NULL DEFAULT '', image_url text NOT NULL DEFAULT '', registration_link text NOT NULL DEFAULT '', organizer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','cancelled','completed')), featured boolean NOT NULL DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view published tournaments" ON tournaments FOR SELECT TO anon, authenticated USING (status = 'published' OR EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins can manage tournaments" ON tournaments FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE TABLE IF NOT EXISTS events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', event_type text NOT NULL DEFAULT 'clinic', location text NOT NULL DEFAULT '', address text NOT NULL DEFAULT '', start_date timestamptz, end_date timestamptz, price numeric(10,2) NOT NULL DEFAULT 0, max_participants integer NOT NULL DEFAULT 0, current_participants integer NOT NULL DEFAULT 0, image_url text NOT NULL DEFAULT '', registration_link text NOT NULL DEFAULT '', organizer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, age_groups text[] NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','cancelled')), featured boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view published events" ON events FOR SELECT TO anon, authenticated USING (status = 'published' OR EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins can manage events" ON events FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE TABLE IF NOT EXISTS programs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), coach_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, title text NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', category text NOT NULL DEFAULT 'skills', level text NOT NULL DEFAULT 'beginner', price numeric(10,2) NOT NULL DEFAULT 0, duration_weeks integer NOT NULL DEFAULT 0, sessions_per_week integer NOT NULL DEFAULT 1, max_participants integer NOT NULL DEFAULT 0, current_participants integer NOT NULL DEFAULT 0, image_url text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', schedule text NOT NULL DEFAULT '', age_min integer NOT NULL DEFAULT 0, age_max integer NOT NULL DEFAULT 99, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')), featured boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
ALTER TABLE programs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view published programs" ON programs FOR SELECT TO anon, authenticated USING (status = 'published' OR EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
CREATE POLICY "Admins can manage programs" ON programs FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE id = (SELECT auth.uid()) AND role = 'admin'));
