import { createClient } from '@supabase/supabase-js'

// --- Configuration ---
// Adjust to your local API port if different
const API_URL = process.env.API_URL || 'http://localhost:3001'
const SUPABASE_URL = process.env.SUPABASE_URL || 'http://localhost:54321'
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || ''

// ANSI Color Codes for QA Output
const COLORS = {
  RESET: '\x1b[0m',
  PASS: '\x1b[32m', // Green
  FAIL: '\x1b[31m', // Red
  INFO: '\x1b[36m', // Cyan
  WARN: '\x1b[33m'  // Yellow
}

const log = {
  info: (msg: string) => console.log(`${COLORS.INFO}ℹ ${msg}${COLORS.RESET}`),
  pass: (msg: string) => console.log(`${COLORS.PASS}✔ PASS:${COLORS.RESET} ${msg}`),
  fail: (msg: string) => console.log(`${COLORS.FAIL}✖ FAIL:${COLORS.RESET} ${msg}`),
  warn: (msg: string) => console.log(`${COLORS.WARN}⚠ WARN:${COLORS.RESET} ${msg}`)
}

async function runTests() {
  console.log(`\n${COLORS.INFO}==========================================`)
  console.log(`ROKU ONE-CLICK PUBLISH QA SUITE`)
  console.log(`==========================================${COLORS.RESET}\n`)

  if (!SUPABASE_KEY) {
    log.warn('No SUPABASE_SERVICE_ROLE_KEY found in environment. Assertions against DB might fail depending on RLS.')
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)
  const mockId = 'TEST-ROKU-' + Date.now()

  // 1. SETUP: Inject Mock Record
  log.info('Phase 1: Setting up mock asset data...')
  const mockAsset = {
    id: '00000000-0000-0000-0000-000000000000', // Mock UUID format might be required depending on schema
    title: 'Automated QA Test Video',
    description: 'This is a test generated by verify_roku_feed.ts',
    duration_seconds: 120,
    storage_path: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    thumbnail_url: 'https://hoopwithher.com/qa-thumb.png',
    status: 'ready',
    category: 'training',
    tags: ['Verification Test'],
    publish_to_roku: true
  }

  // Attempt UUID fix if strict UUID is enforced in the database
  try {
    const { data: insertedAsset, error: insertError } = await supabase
      .from('media_assets')
      .insert({ ...mockAsset, id: crypto.randomUUID() })
      .select('id')
      .single()

    if (insertError) {
      log.fail(`Could not insert mock record. Supabase Error: ${insertError.message}`)
      // If DB is totally down locally, we will still try the GET request but tests will likely fail
    } else {
      mockAsset.id = insertedAsset.id
      log.pass(`Mock asset injected successfully with ID: ${mockAsset.id}`)
    }
  } catch (e) {
    log.warn('Failed to insert mock data using crypto.randomUUID, trying without explicit ID.')
    const { data: insertedAsset, error: insertError } = await supabase
      .from('media_assets')
      .insert({ 
        title: mockAsset.title, description: mockAsset.description, 
        duration_seconds: mockAsset.duration_seconds, storage_path: mockAsset.storage_path, 
        thumbnail_url: mockAsset.thumbnail_url, status: mockAsset.status, 
        category: mockAsset.category, tags: mockAsset.tags, 
        publish_to_roku: mockAsset.publish_to_roku 
      })
      .select('id')
      .single()
      
      if (insertedAsset) mockAsset.id = insertedAsset.id
  }

  // 2. EXECUTE: Fetch Express Endpoint
  log.info('\nPhase 2: Executing API Request...')
  let response, feedJson
  try {
    const fetchUrl = `${API_URL}/api/roku/feed`
    log.info(`Fetching GET ${fetchUrl}`)
    response = await fetch(fetchUrl)
    feedJson = await response.json()
  } catch (err: any) {
    log.fail(`API Request Failed. Is the Express server running on ${API_URL}? Error: ${err.message}`)
    await cleanup(supabase, mockAsset.id)
    process.exit(1)
  }

  // 3. ASSERT: Validate Payload
  log.info('\nPhase 3: Running Assertions...')
  let hasFailures = false

  // Assertion 1: HTTP Status
  if (response.status === 200) {
    log.pass(`HTTP Status Code is 200`)
  } else {
    log.fail(`HTTP Status Code was ${response.status}`)
    hasFailures = true
  }

  // Assertion 2: Cache-Control Headers
  const cacheHeader = response.headers.get('cache-control')
  if (cacheHeader && cacheHeader.includes('max-age=3600') && cacheHeader.includes('public')) {
    log.pass(`Cache-Control header is robust: ${cacheHeader}`)
  } else {
    log.fail(`Cache-Control header missing or incorrect. Received: ${cacheHeader}`)
    hasFailures = true
  }

  // Assertion 3: Schema Conformance (Direct Publisher)
  if (feedJson.providerName === "HOOP WITH HER" && feedJson.lastUpdated && Array.isArray(feedJson.movies)) {
    log.pass(`JSON Schema conforms to Direct Publisher spec (providerName, lastUpdated, movies array exist)`)
  } else {
    log.fail(`JSON Schema invalid. Missing required root keys.`)
    hasFailures = true
  }

  // Assertion 4: Mock Data verification
  const foundMock = feedJson.movies?.find((m: any) => m.title === mockAsset.title)
  if (foundMock) {
    log.pass(`Mock asset successfully found in JSON feed.`)
    
    // Check groupings/tags
    if (foundMock.tags && foundMock.tags.includes('Verification Test')) {
      log.pass(`Asset correctly retained grouping tag: "Verification Test"`)
    } else {
      log.fail(`Asset grouping tags missing or incorrect.`)
      hasFailures = true
    }

    // Check content structure
    if (foundMock.content?.videos?.[0]?.url === mockAsset.storage_path) {
      log.pass(`HLS stream URL successfully mapped to Roku content block.`)
    } else {
      log.fail(`HLS stream URL mapping failed.`)
      hasFailures = true
    }

  } else {
    log.fail(`Mock asset NOT found in feed. Did the query filter 'publish_to_roku=true' fail?`)
    hasFailures = true
  }

  // Print final JSON structure for visual review
  console.log(`\n${COLORS.INFO}--- ROKU JSON FEED SNAPSHOT ---${COLORS.RESET}`)
  console.log(JSON.stringify(feedJson, null, 2))
  console.log(`${COLORS.INFO}-------------------------------${COLORS.RESET}`)

  // 4. TEARDOWN: Clean up Supabase
  await cleanup(supabase, mockAsset.id)

  console.log(`\n${COLORS.INFO}==========================================${COLORS.RESET}`)
  if (hasFailures) {
    console.log(`${COLORS.FAIL}QA RUN FAILED. Fix issues above.${COLORS.RESET}`)
    process.exit(1)
  } else {
    console.log(`${COLORS.PASS}QA RUN PASSED SUCCESSFULLY! The pipeline is ready.${COLORS.RESET}`)
    process.exit(0)
  }
}

async function cleanup(supabase: any, id: string) {
  log.info('\nPhase 4: Teardown...')
  if (id !== '00000000-0000-0000-0000-000000000000') {
    const { error } = await supabase.from('media_assets').delete().eq('id', id)
    if (error) {
      log.fail(`Failed to clean up mock asset ${id}. You may need to delete it manually.`)
    } else {
      log.pass(`Mock asset ${id} deleted from database.`)
    }
  } else {
    log.info('No DB asset to clean up.')
  }
}

// Execute
runTests()
